package com.cheq.retail.sharePreferences

interface SharePrefsKeys {

    companion object {
        const val CHEQ_USER_ID: String = "CHEQ_USER_ID"
        const val MOBILE_NUMBER: String = "MOBILE_NUMBER"
        const val DEVICE_ID: String = "DEVICE_ID"
        const val ACCESS_TOKEN: String = "ACCESS_TOKEN"
        const val REFRESH_TOKEN: String = "REFRESH_TOKEN"
        const val IS_LOGGED_IN: String = "IS_LOGGED_IN"
        const val APP_INSTALLED: String = "APP_INSTALLED"
        const val USER_EMAIL: String = "USER_EMAIL"
        const val FIRST_NAME: String = "FIRST_NAME"
        const val MESSAGE_Id: String = "message_id"
        const val LAST_NAME: String = "LAST_NAME"
        const val DOB: String = "DOB"
        const val PAN_CARD: String = "PAN_CARD"
        const val LAST_SYNC_TIME: String = "LAST_SYNC_TIME"
        const val QUICK_LOGIN_AVAILABLE = "QUICK_LOGIN_AVAILABLE"
        const val IS_UNLOCKED = "IS_UNLOCKED"
        const val IS_EMANDATE_COMPLETE = "IS_EMANDATE_COMPLETE"
        const val IS_PERMISSION_DENIED = "IS_PERMISSION_DENIED"
        const val IS_LINK_EMAIL_CLICKED = "IS_LINK_EMAIL_CLICKED" //16
        const val IS_CARD_ACTIVATE = "is_card_activate" //16
        const val IS_PAYMENT_FAILED = "is_payment_failed"
        const val IS_CARD_SECURE = "is_card_secure" //16
        const val IS_USER_AUTHENTICATE = "is_user_authenticate" //16
        const val IS_BACK_PRESSED = "is_back_pressed"

        // events logs for on boarding screen

        const val CVP_ONE = "CVP_one"
        const val CVP_THREE = "CVP_three"
        const val SPLASH_SCREEN = "splashscreen"
        const val CVP_TWO = "CVP_two"
        const val PERMISSIONS = "permissions"
        const val OB_MOBILE_NUMBER = "mobile_number"
        const val PERSONAL_DETAILS = "personal_details"
        const val VERIFY_OTP = "verify_otp"
        const val FETCHING_DETAIL = "fetching_details"
        const val CONSENTS = "consents"
        const val SUCCESS = "success"
        const val NO_PRODUCT_FOUND = "no_products_found"
        const val PERSONAL_DETAILS_ADDITIONAL = "personal_details_additional"
        const val OB_Add_New_Clicked = "OB_Add_New_Clicked"
        const val LOGIN = "login"
        const val OB_CVP_ONE_CLICK = "Ob_CVP_One_Clicked"
        const val OB_CVP_ONE_SKIPPED = "Ob_CVP_One_Skipped"
        const val OB_CVP_TWO_CLICKED = "Ob_CVP_Two_Clicked"
        const val OB_CVP_TWO_SKIPPED = "Ob_CVP_Two_Skipped"
        const val OB_CVP_TWO_BACK_CLICKED = "Ob_CVP_Two_BackClicked"
        const val OB_CVP_THREE_CLICKED = "Ob_CVP_Three_Clicked"
        const val OB_CVP_THREE_BACK_CLICKED = "Ob_CVP_Three_BackClicked"
        const val OB_NOTIFICATION_PERMISSION_ALLOWED = "Ob_Notification_Permission_Allowed"
        const val OB_NOTIFICATION_PERMISSION_DENIED = "Ob_Notification_Permission_Denied"
        const val OB_PERMISSION_CLICKED = "Ob_Permissions_Clicked"
        const val OB_PHONE_PERMISSION_ALLOWED = "Ob_Phone_Permission_Allowed"
        const val OB_SMS_PERMISSION_ALLOWED = "Ob_SMS_Permission_Allowed"
        const val OB_SMS_Recieve_PERMISSION_ALLOWED = "Ob_SMS_Recieve_Permission_Allowed"
        const val OB_MOBILE_NUMBER_SELECTED = "Ob_Mobile_Number_Selected"
        const val OB_MOBILE_NUMBER_ENTERED = "Ob_Mobile_Number_Entered"
        const val OB_OTP_ENTERED = "Ob_OTP_Entered"
        const val OB_OTP_CLICKED = "Ob_OTP_Clicked"
        const val OB_SMS_PERMISSION_DENIED = "Ob_SMS_Permission_Denied"
        const val OB_SMS_Recieve_PERMISSION_DENIED = "Ob_SMS_Recieve_Permission_Denied"
        const val OB_PHONE_PERMISSION_DENIED = "Ob_Phone_Permission_Denied"
        const val OB_MOBILE_NUMBER_CLICKED = "Ob_Mobile_Number_Clicked"
        const val OB_OTP_RESEND_CLICKED = "Ob_OTP_Resend_Clicked"
        const val OB_OTP_EDIT_BACK_CLICKED = "Ob_OTP_Edit_BackClicked"
        const val OB_OTP_REQUEST_CALL_CLICKED = "Ob_OTP_RequestCall_Clicked"
        const val OB_REFERRAL_PAYLOAD_CHECK = "Ob_referral_payload_check"
        const val OB_REFERRAL_SAVE_FAIL = "Ob_referral_save_fail"
        const val OB_OTP_TIMEOUT_VIEWED = "Ob_OTP_Timeout_Viewed"
        const val OB_PERSONAL_DETAIL_FNAME_ENTERED = "Ob_PersonalDetails_FName_Entered"
        const val OB_PERSONAL_DETAIL_EMAIL_ENTERED = "Ob_PersonalDetails_Email_Entered"
        const val OB_PERSONAL_DETAIL_FNAME_CLICKED = "Ob_PersonalDetails_FName_Clicked"
        const val OB_PERSONAL_DETAIL_LNAME_ENTERED = "Ob_PersonalDetails_LName_Entered"
        const val OB_PERSONAL_DETAIL_LNAME_CLICKED = "Ob_PersonalDetails_LName_Clicked"
        const val OB_PERSONAL_DETAIL_CLICKED = "Ob_PersonalDetails_Clicked"
        const val OB_WHATSAPP_CONSENT_CHECKBOX_SELECTED = "Ob_WhatsAppConsent_Checkbox_Selected"
        const val OB_PERSONAL_DETAIL_EMAIL_CLICKED = "Ob_PersonalDetails_Email_Clicked"
        const val OB_BUREAU = "Ob_BureauConsent_Checkbox_Selected"
        const val OB_WHATSAPP_CONSENT_CHECKBOX_DESELECTED = "Ob_WhatsAppConsent_Checkbox_Deselected"
        const val OB_SUCCESS_CONTINUE = "Ob_Success_Continue"
        const val Onboarding_BureauConsent_T_C_Clicked = "Onboarding_BureauConsent_T&C_Clicked"
        const val OB_PERSONAL_DETAIL_DOB_ENTERED = "Ob_PersonalDetails_DOB_Entered"
        const val OB_PERSONAL_DETAIL_ADDITIONAL_CLICKED = "Ob_PersonalDetails_Additional_Clicked"
        const val OB_CONSENT_CLICKED = "Ob_Consents_Clicked"
        const val OB_LOGIN_CLICKED = "Ob_Login_Clicked"
        const val OB_ADD_NEW_CLICKED = "Ob_Add_New_Clicked"
        const val OB_PERSONAL_DETAIL_PAN_ENTERED = "Ob_PersonalDetails_PAN_Entered"
        const val Onboarding_PANandDOB_Clicked = "Onboarding_PANandDOB_Clicked"
        const val OB_LOGIN_DIFFERENT_USER_CLICKED = "Ob_Login_DifferentUser_Clicked"
        const val OB_LOGIN_AUTH_ENTERED = "Ob_Login_Auth_Entered"
        const val OB_LOGIN_AUTH_VIEWED = "Ob_Login_Auth_Viewed" //73
        const val Onboarding_PrivacyPolicy_Clicked = "Onboarding_PrivacyPolicy_Clicked" //73
        const val Onboarding_T_C_Clicked = "Onboarding_T&C_Clicked"
        const val Onboarding_AddProduct_Clicked = "Onboarding_AddProduct_Clicked"
        const val Onboarding_MakePayment_Clicked = "Onboarding_MakePayment_Clicked"
        const val Onboarding_ExploreCheQ_Clicked = "Onboarding_ExploreCheQ_Clicked"


        // events logs for credit card activation  screen


        const val CC_Activation_Other_Card_Detail = "CC_Activation_Other_Card_Detail"
        const val CC_Activation_Verify_Otp = "CC_Activation_Verify_Otp"
        const val CC_Activation_Enter_Card_Number = "CC_Activation_Enter_Card_Number"
        const val CC_Activation_Card_Number_Entered = "CC_Activation_Card_Number_Entered"
        const val CC_Activation_Pending = "CC_Activation_Pending"
        const val CC_Activation_Expiry_Entered = "CC_Activation_Expiry_Entered"
        const val CC_Activation_Failed = "CC_Activation_Failed"
        const val CC_Activation_CVV_Entered = "CC_Activation_CVV_Entered"
        const val CC_Activation_CardNumber_Clicked = "CC_Activation_CardNumber_Clicked"
        const val CC_Activation_EditName_Entered = "CC_Activation_EditName_Entered"
        const val CC_Activation_EditName_Clicked = "CC_Activation_EditName_Clicked"
        const val CC_Activation_OTP_Entered = "CC_Activation_OTP_Entered"
        const val CC_Activation_OTP_Clicked = "CC_Activation_OTP_Clicked"
        const val CC_Activation_OTP_RequestCall_Clicked = "CC_Activation_OTP_RequestCall_Clicked"
        const val CC_Activation_OTP_Edit_BackClicked = "CC_Activation_OTP_Edit_BackClicked"
        const val CC_Activation_Retry = "CC_Activation_Retry"
        const val CC_Payment_Pending = "CC_Payment_Pending"
        const val LOAN_Payment_Pending = "LOAN_Payment_Pending"
        const val CC_Payment_LOADING = "CC_Payment_LOADING"
        const val LOAN_Payment_LOADING = "LOAN_Payment_LOADING"
        const val CC_Activation_Success_Nudge2 = "CC_Activation_Success_Nudge2"
        const val CC_Payment_Failed = "CC_Payment_Failed"
        const val LOAN_Payment_SUCCESS = "LOAN_Payment_SUCCESS"
        const val LOAN_Payment_Failed = "LOAN_Payment_Failed"
        const val CC_Payment_Select_Amount = "CC_Payment_Select_Amount"
        const val LOAN_Payment_Select_Amount = "LOAN_Payment_Select_Amount"
        const val LOAN_Payment_Select_PAYMENT_METHOD = "LOAN_Payment_Select_PAYMENT_METHOD"
        const val CC_Payment_Select_Payment_Method = "CC_Payment_Select_Payment_Method"
        const val CC_Activation_Success_Nudge1 = "CC_Activation_Success_Nudge1"
        const val CC_Payment_Review_Detail = "CC_Payment_Review_Detail"
        const val LOAN_Payment_Review_Detail = "LOAN_Payment_Review_Detail"
        const val CC_Activation_Success_Clicked = "CC_Activation_Success_Clicked"
        const val CC_Activation_Success = "CC_Activation_Success"
        const val CC_Activation_Failed_BackClicked = "CC_Activation_Success"
        const val CC_Payment_Success = "CC_Payment_Success"
        const val CC_Payment_TotalDue_Clicked = "CC_Payment_TotalDue_Clicked"
        const val CC_Payment_MinimumDue_Clicked = "CC_Payment_MinimumDue_Clicked"
        const val CC_Payment_SelectAmount_Clicked = "CC_Payment_SelectAmount_Clicked"
        const val CC_Payment_Custom_Clicked = "CC_Payment_Custom_Clicked"
        const val CC_Payment_SelectAmount_BackClicked = "CC_Payment_SelectAmount_BackClicked"
        const val CC_Payment_Custom_Entered = "CC_Payment_Custom_Entered"
        const val CC_Payment_RewardsOption_Clicked = "CC_Payment_RewardsOption_Clicked"
        const val CC_Payment_Rewards_KnowMore_Clicked = "CC_Payment_Rewards_KnowMore_Clicked"
        const val CC_Payment_Rewards_KnowMore_BackClicked =
            "CC_Payment_Rewards_KnowMore_BackClicked"
        const val CC_Payment_UPI_Search_Entered = "CC_Payment_UPI_Search_Entered"
        const val CC_Payment_UPI_SeeAll_Clicked = "CC_Payment_UPI_SeeAll_Clicked"
        const val CC_Payment_UPI_ALL_SeeAll_Clicked = "CC_Payment_UPI_ALL_SeeAll_Clicked"
        const val CC_Payment_NetBanking_SeeAll_Clicked = "CC_Payment_NetBanking_SeeAll_Clicked"
        const val CC_Payment_ALL_NetBanking_SeeAll_Clicked =
            "CC_Payment_ALL_NetBanking_SeeAll_Clicked"
          const val LOAN_Payment_ALL_NetBanking_SeeAll_Clicked =
            "LOAN_Payment_ALL_NetBanking_SeeAll_Clicked"


        const val CC_Payment_PreferredMethod_Clicked = "CC_Payment_PreferredMethod_Clicked"
        const val CC_Payment_NetBanking_Search_Entered = "CC_Payment_NetBanking_Search_Entered"
        const val CC_Payment_UPI_Clicked = "CC_Payment_UPI_Clicked"
        const val CC_Payment_RewardsAmount_Entered = "CC_Payment_RewardsAmount_Entered"
        const val CC_Payment_RewardsAmount_Clicked = "CC_Payment_RewardsAmount_Clicked"
        const val CC_Payment_DebitCard_AddNew_Clicked = "CC_Payment_DebitCard_AddNew_Clicked"
        const val LOAN_Payment_DebitCard_AddNew_Clicked = "LOAN_Payment_DebitCard_AddNew_Clicked"
        const val CC_Payment_DebitCard_KnowMore_Clicked = "CC_Payment_DebitCard_KnowMore_Clicked"
        const val CC_Payment_DebitCard_Clicked = "CC_Payment_DebitCard_Clicked"
        const val CC_Payment_DebitCard_SeeAll_Clicked = "CC_Payment_DebitCard_SeeAll_Clicked"
        const val CC_Payment_NetBanking_Clicked = "CC_Payment_NetBanking_Clicked"
        const val CC_Payment_DebitCard_CardNumber_Entered =
            "CC_Payment_DebitCard_CardNumber_Entered"
        const val CC_Payment_DebitCard_CVV_Entered = "CC_Payment_DebitCard_CVV_Entered"
        const val CC_Payment_Failed_BackClicked = "CC_Payment_Failed_BackClicked"
        const val CC_Payment_DebitCard_Checkbox_Deselected =
            "CC_Payment_DebitCard_Checkbox_Deselected"
        const val CC_Payment_DebitCard_Expiry_Entered = "CC_Payment_DebitCard_Expiry_Entered"
        const val CC_Payment_DebitCard_Checkbox_Selected = "CC_Payment_DebitCard_Checkbox_Selected"
        const val CC_Payment_Success_ViewDetails_Clicked = "CC_Payment_Success_ViewDetails_Clicked"
        const val CC_Payment_DebitCard_Name_Entered = "CC_Payment_DebitCard_Name_Entered"
        const val CC_Payment_Review_EditMethod_Clicked = "CC_Payment_Review_EditMethod_Clicked"
        const val CC_Payment_Success_Nudge1 = "CC_Payment_Success_Nudge1"
        const val CC_Payment_DebitCard_AddNew_BackClicked =
            "CC_Payment_DebitCard_AddNew_BackClicked"
        const val CC_Payment_Review_Clicked = "CC_Payment_Review_Clicked"
        const val CC_Payment_Review_BackClicked = "CC_Payment_Review_BackClicked"
        const val Pay_Together_ReferAndEarn_Banner_Clicked = "Pay_Together_ReferAndEarn_Banner_Clicked"
        const val Loan_Payment_ReferAndEarn_Banner_Clicked = "Loan_Payment_ReferAndEarn_Banner_Clicked"
        const val CC_Payment_ReferAndEarn_Banner_Clicked = "CC_Payment_ReferAndEarn_Banner_Clicked"
        const val CC_Payment_Success_Nudge2 = "CC_Payment_Success_Nudge2"
        const val CC_Payment_Success_Nudge3 = "CC_Payment_Success_Nudge3"
        const val LOAN_ADDITION_Success_PAYNOW_CLICKED = "LOAN_ADDITION_Success_PAYNOW_CLICKED"
        const val LOAN_Payment_Success_CLICKED = "LOAN_Payment_Success_CLICKED"
        const val CC_Payment_Success_Clicked = "CC_Payment_Success_Clicked"
        const val CC_Payment_Retry = "CC_Payment_Retry"  // 133
        const val OB_WAITLIST_SUCESS_REFER_NOW_CLICKED = "OB_WAITLIST_SUCESS_REFER_NOW_CLICKED"  // 133
        const val OB_WAITLIST_SUCESS_SEE_REFER_CLICKED = "OB_WAITLIST_SUCESS_SEE_REFER_CLICKED"  // 133
        const val OB_WAITLIST_SUCESS_T_AND_C = "OB_WAITLIST_SUCESS_T_AND_C"  // 133
        const val OB_WAITLIST_SUCESS_HELP_CLICKED = "OB_WAITLIST_SUCESS_HELP_CLICKED"  // 133
        const val OB_WAITLIST_SUCESS_REWARDS_CLICKED = "OB_WAITLIST_SUCESS_REWARDS_CLICKED"  // 133
        const val OB_WAITLIST_DECLINE_HELP_CLICKED = "OB_WAITLIST_DECLINE_HELP_CLICKED"  // 133
        const val ACCOUNT_NEED_HELP_CLICKED = "ACCOUNT_NEED_HELP_CLICKED"
        const val ACCOUNT_PERSONAL_DETAIL_CLICKED = "ACCOUNT_PERSONAL_DETAIL_CLICKED"
        const val Accounts_TransactionHistory_Clicked = "Accounts_TransactionHistory_Clicked"
        const val Accounts_Logout_Clicked = "Accounts_Logout_Clicked"
        const val Accounts_TermsPolicies_Clicked = "Accounts_TermsPolicies_Clicked"
        const val Accounts_LogoutAccept_Clicked = "Accounts_LogoutAccept_Clicked"
        const val Accounts_LogoutCancel_Clicked = "Accounts_LogoutCancel_Clicked"

        const val CC_Verification_Consent_Clicked = "CC_Verification_Consent_Clicked"  // 133
        const val OB_LOADING = "OB_LOADING"  // 133
        const val OB_WAIT_LISTED_SUCESS = "OB_WAIT_LISTED_SUCESS"  // 133
        const val OB_WAIT_LISTED_PENDING = "OB_WAIT_LISTED_PENDING"

        const val OB_WAIT_LISTED_DECL = "OB_WAIT_LISTED_DECL"  // 133
        const val OB_SUCESS = "OB_SUCESS"  // 133
        const val CC_VERIFICATION_CONSENT_TO_SECURE = "CC_VERIFICATION_CONSENT_TO_SECURE"  // 133


        //Deeplink event constants
        const val DEEP_LINK_NOT_FOUND = "DEEP_LINK_NOT_FOUND"
        const val DEEPLINK_ERROR = "DEEPLINK_ERROR"
        const val DEEPLINK_SUBSCRIPTION_FAILED = "DEEPLINK_SUBSCRIPTION_FAILED"
        const val REFERRER_ID_NOT_FOUND = "REFERRER_ID_NOT_FOUND"
        const val AF_ATTRIBUTION_FAILED = "AF_ATTRIBUTION_FAILED"
        const val AF_CONVERSION_DATA_FAILED = "AF_CONVERSION_DATA_FAILED"

        // Events logs for EMandate
        const val EMandate_Select_bank = "EMandate_Select_bank"
        const val EMandate_Registration_Failed = "EMandate_Registration_Failed"
        const val EMandate_Choose_Auth_Method = "EMandate_Choose_Auth_Method"
        const val EMandate_Register_Pending = "EMandate_Register_Pending"
        const val EMandate_Enter_Account_Detail = "EMandate_Select_bank"
        const val EMandate_Intro = "EMandate_Intro"
        const val EMandate_Enable_AutoPay = "EMandate_Enable_AutoPay"
        const val Emandate_Bank_Search_Entered = "Emandate_Bank_Search_Entered"
        const val Emandate_Consent_Checkbox_Selected = "Emandate_Consent_Checkbox_Selected"
        const val EMandate_Register_Success = "EMandate_Register_Success"
        const val Emandate_Bank_Clicked = "Emandate_Bank_Clicked"
        const val Emandate_Consent_Checkbox_Deselected = "Emandate_Consent_Checkbox_Deselected"
        const val Emandate_Introduction_BackClicked = "Emandate_Introduction_BackClicked"
        const val Emandate_IFSC_Entered = "Emandate_IFSC_Entered"
        const val Emandate_Help_Clicked = "Emandate_Help_Clicked"
        const val Emandate_Bank_BackClicked = "Emandate_Bank_BackClicked"
        const val Emandate_Introduction_Clicked = "Emandate_Introduction_Clicked"
        const val Emandate_BankAccountNumber_Entered = "Emandate_BankAccountNumber_Entered"
        const val Emandate_AccountHolderName_Entered = "Emandate_AccountHolderName_Entered"
        const val Emandate_BankAccountDetails_Clicked = "Emandate_BankAccountDetails_Clicked"
        const val Emandate_BankAccountDetails_BackClicked =
            "Emandate_BankAccountDetails_BackClicked"
        const val Emandate_AuthVia_DebitCard_Clicked = "Emandate_AuthVia_DebitCard_Clicked"
        const val Emandate_AuthVia_NetBanking_Clicked = "Emandate_AuthVia_NetBanking_Clicked"
        const val Emandate_Success_Clicked = "Emandate_Success_Clicked"
        const val Emandate_AuthVia_Aadhar_Clicked = "Emandate_AuthVia_Aadhar_Clicked"
        const val Emandate_AuthenticationMethod_BackClicked =
            "Emandate_AuthenticationMethod_BackClicked"
        const val Emandate_AuthenticationMethod_Clicked = "Emandate_AuthenticationMethod_Clicked"
        const val Emandate_Registration_Retry = "Emandate_Registration_Retry"
        const val Emandate_Success_BackClicked = "Emandate_Success_BackClicked"
        const val Emandate_Success_Nudge1 = "Emandate_Success_Nudge1"
        const val Emandate_Success_Nudge2 = "Emandate_Success_Nudge2"
        const val Emandate_AutopayEnable_BackClicked = "Emandate_AutopayEnable_BackClicked" // 165


        // Events logs for Autopay
        const val Autopay_Product1_MinDue_Clicked = "Autopay_Product1_MinDue_Clicked"
        const val Autopay_Product2_Deselected = "Autopay_Product2_Deselected"
        const val Autopay_Product1_Deselected = "Autopay_Product1_Deselected"
        const val Autopay_Product1_Selected = "Autopay_Product1_Selected"
        const val Autopay_Product2_MinDue_Clicked = "Autopay_Product2_MinDue_Clicked"
        const val Autopay_Product1_TotalDue_Clicked = "Autopay_Product1_TotalDue_Clicked"
        const val Autopay_Product2_TotalDue_Clicked = "Autopay_Product2_TotalDue_Clicked"
        const val Autopay_Product2_Selected = "Autopay_Product2_Selected"  //173


        // Events logs for CheqSafe

        const val CheqSafe_Pending = "CheqSafe_Pending"
        const val CheqSafe_Select_Mail = "CheqSafe_Select_Mail"
        const val CheqSafe_Introduction_Clicked = "CheqSafe_Introduction_Clicked"
        const val CheqSafe_EmailClient_Gmail_Selected = "CheqSafe_EmailClient_Gmail_Selected"
        const val CheqSafe_Success = "Cheq_Safe_Success"
        const val CheqSafe_NoStatementFound = "CheqSafe_NoStatementFound"
        const val CheqSafe_Introduction = "CheqSafe_Introduction"
        const val CheqSafe_Failed = "CheqSafe_Failed"
        const val CheqSafe_Introduction_BackClicked = "CheqSafe_Introduction_BackClicked"
        const val CheqSafe_EmailAccess_Denied = "CheqSafe_EmailAccess_Denied"
        const val CheqSafe_EmailClient_Yahoo_Selected = "CheqSafe_EmailClient_Yahoo_Selected"
        const val CheqSafe_EmailClient_Hotmail_Selected = "CheqSafe_EmailClient_Hotmail_Selected"
        const val CheqSafe_Success_Clicked = "CheqSafe_Success_Clicked"
        const val CheqSafe_EmailClient_Outlook_Selected = "CheqSafe_EmailClient_Outlook_Selected"
        const val CheqSafe_EmailClient_Live_Selected = "CheqSafe_EmailClient_Live_Selected"
        const val CheqSafe_EmailAccess_Allowed = "CheqSafe_EmailAccess_Allowed"
        const val CheqSafe_Access_Denied = "CheqSafe_Access_Denied"
        const val CheqSafe_SelectEmail_Clicked = "CheqSafe_SelectEmail_Clicked"
        const val CheqSafe_SelectEmail_Selected = "CheqSafe_SelectEmail_Selected"
        const val CheqSafe_Success_BackClicked = "CheqSafe_Success_BackClicked"
        const val CheqSafe_Failed_Retry = "CheqSafe_Failed_Retry"
        const val CheqSafe_Access_Retry = "CheqSafe_Access_Retry"
        const val CheqSafe_StatementNotFound_BackClicked =
            "CheqSafe_StatementNotFound_BackClicked" // 196

        // Events logs for CheqSafe
        const val Loan_Activation_Select_Lender = "Loan_Activation_Select_Lender"
        const val Loan_Activation_Failed = "Loan_Activation_Failed"
        const val Loan_Activation_Success = "Loan_Activation_Success"
        const val Loan_Activation_Enter_Detail = "Loan_Activation_Enter_Detail"
        const val Loan_Activation_Search_Entered = "CheqSafe_Failed_BackClicked"
        const val Loan_Activation_Pending = "Loan_Activation_Pending"
        const val Loan_Activation_Retry = "Loan_Activation_Retry"
        const val Loan_Activation_Lender_BackClicked = "Loan_Activation_Lender_BackClicked"
        const val Loan_Activation_Lender_Clicked = "Loan_Activation_Lender_Clicked"
        const val Loan_Activation_DOB_Entered = "Loan_Activation_DOB_Entered"
        const val Loan_Activation_MobileNumber_Entered = "Loan_Activation_MobileNumber_Entered"
        const val Loan_Activation_Success_PayNow_Clicked = "Loan_Activation_Success_PayNow_Clicked"
        const val Loan_Activation_OtherDetails_Entered = "Loan_Activation_OtherDetails_Entered"
        const val Loan_Activation_LoanAccountNumber_Entered =
            "Loan_Activation_LoanAccountNumber_Entered"
        const val Loan_Activation_Success_Nudge2 = "Loan_Activation_Success_Nudge2"
        const val Loan_Activation_Success_Clicked = "Loan_Activation_Success_Clicked"
        const val Loan_Activation_Success_Nudge1 = "Loan_Activation_Success_Nudge1"
        const val Loan_select_Amount = "Loan_select_Amount"
        const val Loan_Activation_BillFetch_Clicked = "Loan_Activation_BillFetch_Clicked"
        const val Loan_Activation_Failed_BackClicked = "Loan_Activation_Failed_BackClicked"
        const val Loan_Payment_TotalDue_Clicked = "Loan_Payment_TotalDue_Clicked"
        const val Loan_Payment_Select_Amount = "Loan_Payment_Select_Amount"
        const val Loan_Payment_Payment_Detail = "Loan_Payment_Payment_Detail"
        const val Loan_Payment_Success = "Loan_Payment_Success"
        const val Loan_Review_Detail = "Loan_Review_Detail"
        const val Loan_Payment_MinimumDue_Clicked = "Loan_Payment_MinimumDue_Clicked"
        const val Loan_Payment_Failed = "Loan_Payment_Failed"
        const val Loan_Payment_Custom_Clicked = "Loan_Payment_Custom_Clicked"
        const val Loan_Payment_Pending = "Loan_Payment_Pending"
        const val Loan_Payment_SelectAmount_Clicked = "Loan_Payment_SelectAmount_Clicked"
        const val Loan_Payment_Select_Payment_Method = "Loan_Payment_Select_Payment_Method"
        const val Loan_Payment_Rewards_KnowMore_Clicked = "Loan_Payment_Rewards_KnowMore_Clicked"
        const val Loan_Payment_Custom_Entered = "Loan_Payment_Custom_Entered"
        const val Loan_Payment_UPI_SeeAll_Clicked = "Loan_Payment_UPI_SeeAll_Clicked"
        const val Loan_Payment_UPI_Search_Entered = "Loan_Payment_UPI_Search_Entered"
        const val Loan_Payment_SelectAmount_BackClicked = "Loan_Payment_SelectAmount_BackClicked"
        const val Loan_Payment_Rewards_KnowMore_BackClicked =
            "Loan_Payment_Rewards_KnowMore_BackClicked"
        const val Loan_Payment_NetBanking_SeeAll_Clicked = "Loan_Payment_NetBanking_SeeAll_Clicked"
        const val Loan_Payment_UPI_Clicked = "Loan_Payment_UPI_Clicked"
        const val Loan_Payment_NetBanking_Search_Entered = "Loan_Payment_NetBanking_Search_Entered"
        const val Loan_Payment_NetBanking_Clicked = "Loan_Payment_NetBanking_Clicked"
        const val Loan_Payment_RewardsAmount_Entered = "Loan_Payment_RewardsAmount_Entered"
        const val Loan_Payment_RewardsAmount_Clicked = "Loan_Payment_RewardsAmount_Clicked"
        const val Loan_Payment_PreferredMethod_Clicked = "Loan_Payment_PreferredMethod_Clicked"
        const val Loan_Payment_RewardsOption_Clicked = "Loan_Payment_RewardsOption_Clicked"
        const val Loan_Payment_DebitCard_SeeAll_Clicked = "Loan_Payment_DebitCard_SeeAll_Clicked"
        const val Loan_Payment_DebitCard_Expiry_Entered = "Loan_Payment_DebitCard_Expiry_Entered"
        const val Loan_Payment_DebitCard_CVV_Entered = "Loan_Payment_DebitCard_CVV_Entered"
        const val Loan_Payment_DebitCard_CardNumber_Entered =
            "Loan_Payment_DebitCard_CardNumber_Entered"
        const val Loan_Payment_DebitCard_Name_Entered = "Loan_Payment_DebitCard_Name_Entered"
        const val Loan_Payment_DebitCard_AddNew_Clicked = "Loan_Payment_DebitCard_AddNew_Clicked"
        const val Loan_Payment_DebitCard_Checkbox_Selected =
            "Loan_Payment_DebitCard_Checkbox_Selected"
        const val Loan_Payment_DebitCard_Checkbox_Deselected =
            "Loan_Payment_DebitCard_Checkbox_Deselected"
        const val Loan_Payment_Review_Clicked = "Loan_Payment_Review_Clicked"
        const val Loan_Payment_Review_EditMethod_Clicked = "Loan_Payment_Review_EditMethod_Clicked"
        const val Loan_Payment_DebitCard_AddNew_BackClicked =
            "Loan_Payment_DebitCard_AddNew_BackClicked"
        const val Loan_Payment_Review_BackClicked = "Loan_Payment_Review_BackClicked"
        const val Loan_Payment_Failed_BackClicked = "Loan_Payment_Failed_BackClicked"
        const val Loan_Payment_Success_ViewDetails_Clicked =
            "Loan_Payment_Success_ViewDetails_Clicked"
        const val Loan_Payment_Success_Clicked = "Loan_Payment_Success_Clicked"
        const val Loan_Payment_Retry = "Loan_Payment_Retry"
        const val Loan_Payment_Success_Nudge1 = "Loan_Payment_Success_Nudge1"
        const val Loan_Payment_Success_Nudge2 = "Loan_Payment_Success_Nudge2" // 256
        const val REWARDS_COIN_BALANCE = "coin_balance"

        const val IS_USER_WAIT_LISTED = "IS_USER_WAIT_LISTED"
        const val IS_WHATSAPP_CHECK = "is_whatsapp_check"

        const val IS_BASE_URLS_AVAIL = "isBaseUrlAvail"
        const val BASE_BANK_MASTER = "bankMaster"
        const val BASE_LOAN_MASTER = "loanMaster"
        const val BASE_BANNER = "banner"
        const val BASE_HTML = "html"
        const val BASE_POLICIES = "policies"
        const val BASE_FAQS = "faqs"
        const val BASE_VOUCHER = "voucher"
        const val BASE_WAITLIST = "waitlist"

        //Referral values
        const val REF_SHORT_URL = "refShortUrl"
        const val REF_BE_URL = "refBEUrl"
        const val REFERRAL_KEY: String = "referralKey"
        const val SSL_KEYS: String = "sslKeys"
        const val HOST: String = "host"
        const val SSL_ENABLED: String = "sslEnabled"
        const val SSL_SAVED: String = "sslSaved"
        const val SSL_DELAY: String = "sslDelay"
        const val ENCRYPTION_KEY: String = "encryptionKey"


        ///Home Events
        const val HOME_TAB = "HOME_TAB"

        //Pay Tab
        const val PAY_TAB = "PAY_TAB"
        const val IS_CARD_SHOWN = "isCardShown"

        //Reward
        const val REWARD_TAB = "REWARD_TAB"
        const val REWARD_TAB_CONVERT_TO_CASH = "REWARD_TAB_CONVERT_TO_CASH"
        const val REWARD_TAB_CONVERT_TO_CASH_ACCOUNT = "REWARD_TAB_CONVERT_TO_CASH_ACCOUNT"
        const val REWARD_TAB_CONVERT_TO_CASH_LOADiNG = "REWARD_TAB_CONVERT_TO_CASH_LOADiNG"
        const val REWARD_TAB_CONVERT_TO_CASH_SUCESS = "REWARD_TAB_CONVERT_TO_CASH_SUCESS"
        const val REWARD_TAB_MERCHANT = "REWARD_TAB_MERCHANT"
        const val REWARD_TAB_REEDEEMING_VOUCHER = "REWARD_TAB_REEDEEMING_VOUCHER"
        const val REWARD_TAB_REEDEEMING_VOUCHER_SUCESS = "REWARD_TAB_REEDEEMING_VOUCHER_SUCESS"
        const val CREDIT_DASH = "CREDIT_DASH"
        const val ACCOUNT_SETTING = "ACCOUNT_SETTING"
        const val LOAN_SELECT_LENDER = "LOAN_SELECT_LENDER"
        const val LOAN_ENTER_DETAIL = "LOAN_ENTER_DETAIL"
        const val LOAN_SUCCESS = "LOAN_SUCCESS"
        const val LOAN_SEARCHING = "LOAN_SEARCHING"
        const val TRANSACTION_HISTORY = "TRANSACTION_HISTORY"
        const val ACCOUNT_SETTING_LOGOUT = "ACCOUNT_SETTING_LOGOUT"
        const val REFERRAL_EARN = "REFERRAL_EARN"
        const val Home_Primary_CTA_Clicked = "Home_Primary_CTA_Clicked"
        const val PAY_TOGETHER_SUCESS = "PAY_TOGETHER_SUCESS"
        const val Home_ReferAndEarn_Banner_Clicked = "Home_ReferAndEarn_Banner_Clicked"
        const val Home_Rewards_Banner_Clicked = "Home_Rewards_Banner_Clicked"
        const val PayTab_AddNew_Clicked = "PayTab_AddNew_Clicked"
        const val ReferAndEarn_InviteYourFriend_Clicked = "ReferAndEarn_InviteYourFriend_Clicked"
        const val Rewards_ConvertToCash_Banner_Clicked = "Rewards_ConvertToCash_Banner_Clicked"
        const val Rewards_ExploreVoucher_Category_Clicked =
            "Rewards_ExploreVoucher_Category_Clicked"
        const val Rewards_ExploreVoucher_SeeAll_Clicked = "Rewards_ExploreVoucher_SeeAll_Clicked"
        const val Rewards_FeaturedDeal_Clicked = "Rewards_FeaturedDeal_Clicked"
        const val REFER_AND_EARN_VIEWED = "/refer-and-earn/nudge"
        const val REFER_AND_EARN_SECONDARY_CLICKED = "ReferAndEarnNudge_Secondary_Clicked"
        const val REFER_AND_EARN_PRIMARY_CLICKED = "ReferAndEarnNudge_Primary_Clicked"

        //Cheq safe
        const val CHEQ_SAFE_STATUS = "CheqSafeStatus"

        //Bill summary
        const val CC_PAYMENT_BILL_SUMMARY_FEES_KNOW_MORE_CLICKED = "CC_Payment_BillSummary_Fees_KnowMore_Clicked"
        const val CC_PAYMENT_BILL_SUMMARY = "/cc-payment/bill-summary"
        const val CC_PAYMENT_BILL_SUMMARY_CLICKED = "CC_Payment_BillSummary_Clicked"
        const val CC_PAYMENT_BILL_SUMMARY_CHANGED_PAYMENT_METHOD_CLICKED = "CC_Payment_BillSummary_ChangePaymentMethod_Clicked"
        const val CC_PAYMENT_BILL_SUMMARY_CANCEL_CLICKED = "CC_Payment_BillSummary_Cancel_Clicked"
        const val CC_PAYMENT_BILL_SUMMARY_PE_KM_CLICKED = "CC_Payment_BillSummary_PotentialEarning_KnowMore_Clicked"

      //Onboarding new events
        const val GET_USER_ID_FIRST_TRY = "GetUserIDSetState_FirstTry"
        const val GET_USER_ID_RETRY = "GetUserIDSetState_Retry"
        const val GET_USER_ID_SUCCESS = "UserIDReceived_StateSuccess"
        const val OTP_ALLOWED_NEW_USER ="GenerateOTPAllowed_NewUser"
        const val OTP_DENIED_NEW_USER ="GenerateOTPDenied_NewUser"
        const val OTP_ALLOWED_EXISTING_USER ="GenerateOTPAllowed_ExistingUser"
        const val OTP_DENIED_EXISTING_USER ="GenerateOTPDenied_ExistingUser"
    }

}