package com.cheq.retail.ui.deeplinkHandler

enum class Pages {
    CARD_PAYMENT,
    SPLASH,
    CVP,
    PERMISSIONS,
    NOTIFICATION_PERMISSION,
    ENTER_PHONE_NUMBER,
    PERSONAL_DETAILS,
    MASTER_CONSENT,
    ACCOUNT_AND_SETTINGS,
    LOADING,
    ADDITIONAL_DETAILS_REQUIRED,
    HOME,
    DASHBOARD,
    CHEQ_SAFE,
    REWARDS,
    TRANSACTION_HISTORY,
    REFERRAL_HISTORY,
    REFER_AND_EARN
}