package com.cheq.retail.ui.login.modelv2.loanv1

import androidx.annotation.Keep
import com.cheq.retail.ui.login.modelv2.productv1.OuterGridGradientColorsX
@Keep
data class LoanMasterRecord(
    val __v: Int,
    val alias: List<String>,
    val billerAdditionalInfoPayment: List<Any>,
    val billerAliasName: String,
    val billerDescription: String,
    val billerEffctvFrom: String,
    val billerEffctvTo: String,
    val billerId: String,
    val billerMode: String,
    val billerName: String,
    val billerOwnerShp: String,
    val billerResponseType: String,
    val billerTempDeactivationEnd: Any,
    val billerTempDeactivationStart: Any,
    val billerTimeOut: Any,
    val blrAdditionalInfo: List<BlrAdditionalInfo>,
    val blrResponseParams: BlrResponseParams,
    val category: String,
    val createdAt: String,
    val customerParamGroups: Any,
    val customerParams: List<CustomerParam>,
    val fetchOption: String,
    val flowType: String,
    val interchangeFee: List<Any>,
    val interchangeFeeConf: List<Any>,
    val isActive: Boolean,
    val isAdhoc: Boolean,
    val isBNPL: Boolean,
    val isBnpl: Boolean,
    val isDeleted: Boolean,
    val isExperianLender: Any,
    val json: Json,
    val logo: String,
    val logoWithName: String,
    val originalLenderName: Any,
    val outerGridGradientColors: OuterGridGradientColorsX,
    val parentBiller: String,
    val parentBillerId: Any,
    val paymentAmountExactness: String,
    val paymentChannelsAllowed: List<PaymentChannelsAllowedX>,
    val paymentModesAllowed: List<PaymentModesAllowedX>,
    val planAdditionalInfo: List<Any>,
    val planMdmRequirement: String,
    val region: String,
    val regionCode: String,
    val state: String,
    val status: String,
    val supportBillValidation: String,
    val supportDeemed: Boolean,
    val supportPendingStatus: Boolean,
    val updatedAt: String
)